image: node:latest

variables:
  SUBFOLDER: "carries-bar"

cache:
  paths:
    - node_modules/

pages:
  script:
    - npm ci
    - npm run build
    - mkdir -p public/${SUBFOLDER}
    - cp -r dist/* public/${SUBFOLDER}/
    # Copy over optional audio assets if they exist in the source directory
    - if [ -d src/public/audio ]; then cp -r src/public/audio public/${SUBFOLDER}/; fi
  artifacts:
    paths:
      - public
  only:
    - main
